project_name: influxdb
builds:
  - goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/influx/
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influx
  - goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/influxd/
    flags:
      - -tags=assets
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influxd
    hooks:
      pre: make generate

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: 'influxdb_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md

s3:
  -
    bucket: dl.influxdata.com
    region: us-east-1
    folder: "influxdb/releases/"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - influxd
    - influx
    image_templates:
      - 'quay.io/influxdb/influxdb:{{ .Env.DOCKER_VERSION }}'
    dockerfile: docker/influxd/Dockerfile
    extra_files:
      - docker/influxd/entrypoint.sh

# Do not make github release
release:
  name_template: "v{{.Version}}"
  prerelease: auto # when we go to GA remove this line
  draft: true      # when we go to GA remove this line
  disable: true    # we keep the artifacts in S3 and link from the website
